/**
 * Realistic Mock Data & Seed Storage
 * Used for development, offline testing, and seamless UI demonstrations.
 */
import { WorkerUser } from '../../types/auth';
import { CustomerProfile } from '../../types/customer';
import { Transaction, TodayStats } from '../../types/transaction';

export const INITIAL_MOCK_WORKER: WorkerUser = {
  id: 'w-101',
  workerId: 'EMP-7842',
  fullName: 'Vikram Singh',
  email: 'vikram.singh@petrolpump.com',
  mobileNumber: '9876543210',
  petrolPumpId: 'pp-01',
  petrolPumpName: 'Downtown City Station',
  branchName: 'Branch #104 (MG Road)',
  role: 'Senior Attendant',
  profilePhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  joiningDate: '2024-01-15T09:00:00.000Z',
  accountStatus: 'active',
  createdAt: '2024-01-15T09:00:00.000Z',
  updatedAt: '2026-09-24T10:00:00.000Z',
};

export const MOCK_CUSTOMERS: CustomerProfile[] = [
  {
    id: 'c-01',
    customerId: 'CUST-8821',
    fullName: 'Rahul Patel',
    mobileNumber: '+91 98234 11223',
    email: 'rahul.patel@gmail.com',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    vehicleNumber: 'MH 12 AB 4590',
    fuelPreference: 'Petrol (Speed/Power)',
    group: {
      groupId: 'grp-01',
      groupName: 'Family Group',
      groupType: 'Family Group',
      discountPercentage: 10,
      description: 'Standard family plan discount on all fuel types',
    },
    status: 'active',
    joinedDate: '2025-03-10T10:00:00.000Z',
    totalRedemptions: 42,
  },
  {
    id: 'c-02',
    customerId: 'CUST-3390',
    fullName: 'Priya Sharma',
    mobileNumber: '+91 97112 33445',
    email: 'priya.sharma@techcorp.in',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=250&q=80',
    vehicleNumber: 'DL 01 CA 8892',
    fuelPreference: 'Diesel',
    group: {
      groupId: 'grp-02',
      groupName: 'TechCorp Corporate Fleet',
      groupType: 'Corporate Fleet',
      discountPercentage: 15,
      description: 'Corporate employee fleet discount',
    },
    status: 'active',
    joinedDate: '2025-06-20T11:30:00.000Z',
    totalRedemptions: 19,
  },
  {
    id: 'c-03',
    customerId: 'CUST-7714',
    fullName: 'Amitabh Verma',
    mobileNumber: '+91 98450 67890',
    email: 'amitabh.v@citytaxi.org',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    vehicleNumber: 'KA 03 TX 1102',
    fuelPreference: 'CNG',
    group: {
      groupId: 'grp-03',
      groupName: 'City Taxi Drivers Union',
      groupType: 'Taxi Union',
      discountPercentage: 8,
      description: 'Registered taxi union commercial discount',
    },
    status: 'active',
    joinedDate: '2025-01-05T08:00:00.000Z',
    totalRedemptions: 118,
  },
  {
    id: 'c-04',
    customerId: 'CUST-5519',
    fullName: 'Sunita Rao',
    mobileNumber: '+91 99887 76655',
    email: 'sunita.rao@vipclub.com',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    vehicleNumber: 'TS 09 XY 9999',
    fuelPreference: 'Petrol (Normal)',
    group: {
      groupId: 'grp-04',
      groupName: 'Premium Club VIP',
      groupType: 'Premium VIP',
      discountPercentage: 12,
      description: 'VIP Gold Member Tier Discount',
    },
    status: 'active',
    joinedDate: '2025-08-14T14:15:00.000Z',
    totalRedemptions: 31,
  },
];

const now = new Date();

// Helper to generate ISO string offset by hours/days
const getOffsetISO = (daysOffset: number, hoursOffset: number = 0, minutesOffset: number = 0): string => {
  const d = new Date(now.getTime());
  d.setDate(d.getDate() - daysOffset);
  d.setHours(d.getHours() - hoursOffset);
  d.setMinutes(d.getMinutes() - minutesOffset);
  return d.toISOString();
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-01',
    transactionId: 'TXN-948201',
    customerId: 'c-01',
    customerName: 'Rahul Patel',
    customerMobile: '+91 98234 11223',
    groupId: 'grp-01',
    groupName: 'Family Group',
    groupType: 'Family Group',
    fuelAmount: 1000,
    discountPercentage: 10,
    discountAmount: 100,
    finalAmount: 900,
    workerId: 'EMP-7842',
    workerName: 'Vikram Singh',
    petrolPumpId: 'pp-01',
    petrolPumpName: 'Downtown City Station',
    branchName: 'Branch #104 (MG Road)',
    status: 'COMPLETED',
    createdAt: getOffsetISO(0, 1, 15), // 1 hour 15 min ago (Today)
    notes: 'Speed Petrol Dispenser #2',
  },
  {
    id: 'tx-02',
    transactionId: 'TXN-948195',
    customerId: 'c-02',
    customerName: 'Priya Sharma',
    customerMobile: '+91 97112 33445',
    groupId: 'grp-02',
    groupName: 'TechCorp Corporate Fleet',
    groupType: 'Corporate Fleet',
    fuelAmount: 2400,
    discountPercentage: 15,
    discountAmount: 360,
    finalAmount: 2040,
    workerId: 'EMP-7842',
    workerName: 'Vikram Singh',
    petrolPumpId: 'pp-01',
    petrolPumpName: 'Downtown City Station',
    branchName: 'Branch #104 (MG Road)',
    status: 'COMPLETED',
    createdAt: getOffsetISO(0, 3, 40), // 3 hours 40 min ago (Today)
    notes: 'Diesel Dispenser #4',
  },
  {
    id: 'tx-03',
    transactionId: 'TXN-948170',
    customerId: 'c-03',
    customerName: 'Amitabh Verma',
    customerMobile: '+91 98450 67890',
    groupId: 'grp-03',
    groupName: 'City Taxi Drivers Union',
    groupType: 'Taxi Union',
    fuelAmount: 750,
    discountPercentage: 8,
    discountAmount: 60,
    finalAmount: 690,
    workerId: 'EMP-7842',
    workerName: 'Vikram Singh',
    petrolPumpId: 'pp-01',
    petrolPumpName: 'Downtown City Station',
    branchName: 'Branch #104 (MG Road)',
    status: 'COMPLETED',
    createdAt: getOffsetISO(0, 5, 20), // 5 hours ago (Today)
    notes: 'CNG Bay #1',
  },
  {
    id: 'tx-04',
    transactionId: 'TXN-947880',
    customerId: 'c-04',
    customerName: 'Sunita Rao',
    customerMobile: '+91 99887 76655',
    groupId: 'grp-04',
    groupName: 'Premium Club VIP',
    groupType: 'Premium VIP',
    fuelAmount: 3500,
    discountPercentage: 12,
    discountAmount: 420,
    finalAmount: 3080,
    workerId: 'EMP-7842',
    workerName: 'Vikram Singh',
    petrolPumpId: 'pp-01',
    petrolPumpName: 'Downtown City Station',
    branchName: 'Branch #104 (MG Road)',
    status: 'COMPLETED',
    createdAt: getOffsetISO(1, 4, 0), // Yesterday
    notes: 'Petrol Dispenser #1',
  },
  {
    id: 'tx-05',
    transactionId: 'TXN-947620',
    customerId: 'c-01',
    customerName: 'Rahul Patel',
    customerMobile: '+91 98234 11223',
    groupId: 'grp-01',
    groupName: 'Family Group',
    groupType: 'Family Group',
    fuelAmount: 1500,
    discountPercentage: 10,
    discountAmount: 150,
    finalAmount: 1350,
    workerId: 'EMP-7842',
    workerName: 'Vikram Singh',
    petrolPumpId: 'pp-01',
    petrolPumpName: 'Downtown City Station',
    branchName: 'Branch #104 (MG Road)',
    status: 'COMPLETED',
    createdAt: getOffsetISO(2, 6, 0), // 2 days ago (This Week)
  },
  {
    id: 'tx-06',
    transactionId: 'TXN-946910',
    customerId: 'c-02',
    customerName: 'Priya Sharma',
    customerMobile: '+91 97112 33445',
    groupId: 'grp-02',
    groupName: 'TechCorp Corporate Fleet',
    groupType: 'Corporate Fleet',
    fuelAmount: 2000,
    discountPercentage: 15,
    discountAmount: 300,
    finalAmount: 1700,
    workerId: 'EMP-7842',
    workerName: 'Vikram Singh',
    petrolPumpId: 'pp-01',
    petrolPumpName: 'Downtown City Station',
    branchName: 'Branch #104 (MG Road)',
    status: 'COMPLETED',
    createdAt: getOffsetISO(5, 2, 0), // 5 days ago (This Week)
  },
  {
    id: 'tx-07',
    transactionId: 'TXN-945200',
    customerId: 'c-03',
    customerName: 'Amitabh Verma',
    customerMobile: '+91 98450 67890',
    groupId: 'grp-03',
    groupName: 'City Taxi Drivers Union',
    groupType: 'Taxi Union',
    fuelAmount: 850,
    discountPercentage: 8,
    discountAmount: 68,
    finalAmount: 782,
    workerId: 'EMP-7842',
    workerName: 'Vikram Singh',
    petrolPumpId: 'pp-01',
    petrolPumpName: 'Downtown City Station',
    branchName: 'Branch #104 (MG Road)',
    status: 'COMPLETED',
    createdAt: getOffsetISO(12, 5, 0), // 12 days ago (This Month)
  },
];
