/**
 * QR Code Validation & OTP Verification Service
 * Validates dynamic 60-second rotating customer QR tokens against the backend.
 * Never trusts unverified payload on device.
 */
import { apiClient } from '../api/apiClient';
import { CONFIG } from '../../constants/config';
import { MOCK_CUSTOMERS } from '../api/mockData';
import {
  QRValidateRequest,
  QRValidateResponse,
  QRErrorCode,
  QRErrorDetails,
} from '../../types/qr';

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export class QRService {
  // Store used tokens in memory for mock session duplicate prevention
  private static usedTokens = new Set<string>();

  /**
   * Validate QR token with backend
   */
  static async validateQRToken(payload: QRValidateRequest): Promise<QRValidateResponse> {
    const rawToken = payload.qrToken.trim();

    if (!rawToken) {
      throw this.createQRError('QR_INVALID', 'The scanned QR code is empty or unreadable.');
    }

    // Call backend endpoint
    const response = await apiClient.post<QRValidateResponse>('/qr/validate', {
      qrToken: rawToken,
      workerId: payload.workerId,
      petrolPumpId: payload.petrolPumpId,
      scannedAt: payload.scannedAt || new Date().toISOString(),
    });

    if (response.success && response.data) {
      return response.data;
    }

    // Isolated Mock Validation Fallback
    if (CONFIG.USE_MOCK_FALLBACK) {
      await sleep(CONFIG.MOCK_DELAY_MS);

      return this.mockValidateQR(rawToken);
    }

    // Translate backend error
    const errCode = (response.error?.code as QRErrorCode) || 'SERVER_ERROR';
    throw this.createQRError(errCode, response.message || 'QR Validation failed');
  }

  /**
   * Verify Customer OTP for discount redemption
   */
  static async verifyOTP(payload: {
    customerId: string;
    qrSessionId: string;
    otp: string;
  }): Promise<{ success: boolean; message: string }> {
    const trimmedOtp = payload.otp.trim();
    if (!trimmedOtp) {
      throw new Error('Please enter the OTP provided by the customer.');
    }

    const response = await apiClient.post<{ success: boolean; message: string }>('/qr/verify-otp', {
      customerId: payload.customerId,
      qrSessionId: payload.qrSessionId,
      otp: trimmedOtp,
    });

    if (response.success && response.data) {
      return response.data;
    }

    if (CONFIG.USE_MOCK_FALLBACK) {
      await sleep(CONFIG.MOCK_DELAY_MS);

      if (trimmedOtp === '000000' || trimmedOtp === '0000') {
        throw new Error('Invalid OTP. Please check the code provided by the customer and try again.');
      }
      if (trimmedOtp === '999999' || trimmedOtp === '9999') {
        throw new Error('OTP has expired. Please ask the customer to generate a new verification OTP.');
      }
      if (trimmedOtp.length < 4) {
        throw new Error('Please enter a valid numeric OTP (4-6 digits).');
      }

      return {
        success: true,
        message: 'OTP verified successfully.',
      };
    }

    throw new Error(response.message || 'OTP verification failed.');
  }

  /**
   * Isolated Mock validation logic for dynamic tokens
   */
  private static mockValidateQR(rawToken: string): QRValidateResponse {
    // Check if token explicitly tests an error scenario
    if (rawToken.toLowerCase().includes('expired')) {
      throw this.createQRError('QR_EXPIRED', 'This QR code expired 60 seconds after generation. Please ask customer to refresh.');
    }
    if (rawToken.toLowerCase().includes('used') || this.usedTokens.has(rawToken)) {
      throw this.createQRError('QR_ALREADY_USED', 'This dynamic QR token has already been redeemed.');
    }
    if (rawToken.toLowerCase().includes('blocked')) {
      throw this.createQRError('CUSTOMER_BLOCKED', 'This customer account has been temporarily suspended by administration.');
    }
    if (rawToken.toLowerCase().includes('notfound') || rawToken.toLowerCase().includes('invalid')) {
      throw this.createQRError('CUSTOMER_NOT_FOUND', 'Unrecognized customer QR code signature. Not found in system.');
    }

    // Try parsing JSON format if generated by modern mobile apps: {"cId":"c-01","ts":1727160000,"sig":"xyz"}
    let customer = MOCK_CUSTOMERS[0]; // Default Rahul Patel (10% Family Group)
    let tokenTimestamp: number | null = null;

    try {
      if (rawToken.startsWith('{') && rawToken.endsWith('}')) {
        const parsed = JSON.parse(rawToken);
        if (parsed.cId) {
          const match = MOCK_CUSTOMERS.find(c => c.id === parsed.cId || c.customerId === parsed.cId);
          if (match) customer = match;
        }
        if (parsed.ts) {
          tokenTimestamp = Number(parsed.ts);
        }
      } else if (rawToken.startsWith('CUST-') || rawToken.startsWith('c-')) {
        const match = MOCK_CUSTOMERS.find(c => c.customerId === rawToken || c.id === rawToken);
        if (match) customer = match;
      } else if (rawToken.includes('priya') || rawToken.includes('corporate')) {
        customer = MOCK_CUSTOMERS[1];
      } else if (rawToken.includes('taxi') || rawToken.includes('amitabh')) {
        customer = MOCK_CUSTOMERS[2];
      } else if (rawToken.includes('vip') || rawToken.includes('sunita')) {
        customer = MOCK_CUSTOMERS[3];
      }
    } catch {
      // Fallback
    }

    // Check expiration if timestamp exists (simulating 60s rule)
    if (tokenTimestamp) {
      const ageSeconds = (Date.now() - tokenTimestamp) / 1000;
      if (ageSeconds > CONFIG.QR_VALIDITY_WINDOW_SECONDS + 10) {
        throw this.createQRError('QR_EXPIRED', 'This QR code has expired (validity is 60 seconds). Please ask customer to refresh.');
      }
    }

    // Generate ephemeral session token for redemption
    const qrSessionId = 'qrsess_' + Math.random().toString(36).substring(2, 12) + '_' + Date.now();
    const expiresAt = new Date(Date.now() + 5 * 60 * 1000).toISOString(); // 5 min checkout window

    return {
      success: true,
      valid: true,
      qrSessionId,
      customer,
      expiresAt,
      discountPercentage: customer.group.discountPercentage,
    };
  }

  /**
   * Mark token as used in mock session
   */
  static markTokenUsed(qrSessionId: string) {
    this.usedTokens.add(qrSessionId);
  }

  /**
   * Helper to format standardized user-friendly QRError
   */
  public static createQRError(code: QRErrorCode, customMessage?: string): Error & QRErrorDetails {
    let title = 'Scan Error';
    let message = customMessage || 'An error occurred while validating the QR code.';
    let canRetry = true;

    switch (code) {
      case 'QR_EXPIRED':
        title = 'QR Code Expired';
        message = customMessage || 'Customer QR codes rotate every 60 seconds for security. Please ask the customer to generate a fresh QR code.';
        break;
      case 'QR_ALREADY_USED':
        title = 'Already Redeemed';
        message = customMessage || 'This one-time QR token was already redeemed. Ask customer to generate a new QR code.';
        break;
      case 'QR_INVALID':
        title = 'Invalid QR Code';
        message = customMessage || 'The scanned QR code is not a valid PetrolPump customer token.';
        break;
      case 'CUSTOMER_NOT_FOUND':
        title = 'Customer Not Found';
        message = customMessage || 'No active customer or group found matching this QR token.';
        break;
      case 'CUSTOMER_BLOCKED':
        title = 'Account Suspended';
        message = customMessage || 'This customer account is inactive or suspended. Cannot redeem discount.';
        canRetry = false;
        break;
      case 'UNAUTHORIZED_WORKER':
        title = 'Unauthorized';
        message = 'Your worker account is not authorized to redeem transactions at this pump.';
        canRetry = false;
        break;
      case 'NETWORK_ERROR':
        title = 'Connection Problem';
        message = 'Unable to connect to server. Please check internet connection and retry.';
        break;
      case 'SERVER_ERROR':
      default:
        title = 'Server Error';
        message = customMessage || 'Something went wrong on the server while validating QR.';
        break;
    }

    const err = new Error(message) as Error & QRErrorDetails;
    err.code = code;
    err.title = title;
    err.message = message;
    err.canRetry = canRetry;
    return err;
  }

  /**
   * Sample dynamic QR token generator for in-app demo/testing
   */
  static generateSampleQRToken(type: 'family' | 'corporate' | 'taxi' | 'vip' | 'expired'): string {
    const ts = Date.now();
    switch (type) {
      case 'family':
        return JSON.stringify({ cId: 'c-01', name: 'Rahul Patel', ts, sig: 'sig_fam_10pct' });
      case 'corporate':
        return JSON.stringify({ cId: 'c-02', name: 'Priya Sharma', ts, sig: 'sig_corp_15pct' });
      case 'taxi':
        return JSON.stringify({ cId: 'c-03', name: 'Amitabh Verma', ts, sig: 'sig_taxi_8pct' });
      case 'vip':
        return JSON.stringify({ cId: 'c-04', name: 'Sunita Rao', ts, sig: 'sig_vip_12pct' });
      case 'expired':
        return 'TOKEN_EXPIRED_TEST_CODE';
      default:
        return JSON.stringify({ cId: 'c-01', ts, sig: 'sig_def' });
    }
  }
}
